const PLANS = 'PLANS';
const UPGRADE = 'UPGRADE';
const USER = 'USER';
const INVOICE = 'INVOICE';
const PROFILE_AVATAR = 'PROFILE_AVATAR';
const UPDATE_USER = 'UPDATE_USER';
const COMPANY_LOGO = 'COMPANY_LOGO';
const UPDATE_COMPANY = 'UPDATE_COMPANY';

export default {
    PLANS,
    UPGRADE,
    USER,
    INVOICE,
    PROFILE_AVATAR,
    UPDATE_USER,
    COMPANY_LOGO,
    UPDATE_COMPANY
}