// create-edit
const GENERATE_NUMBER = 'GENERATE_NUMBER';

// documents
const GET_INVOICES = 'GET_INVOICES';
const GET_DELETED_INVOICES = 'GET_DELETED_INVOICES';
const GET_TOTAL_BY_CURRENCY = 'GET_TOTAL_BY_CURRENCY';
const GET_TOTAL_BY_CURRENCY_STATUS = 'GET_TOTAL_BY_CURRENCY_STATUS';
const DELETE_INVOICE = 'DELETE_INVOICE';
const GET_INVOICE_DATA = 'GET_INVOICE_DATA';

// reports
const GET_FILTERED_DATA = 'GET_FILTERED_DATA';


export default {
    GENERATE_NUMBER,
    GET_INVOICES,
    GET_DELETED_INVOICES,
    GET_TOTAL_BY_CURRENCY,
    GET_TOTAL_BY_CURRENCY_STATUS,
    DELETE_INVOICE,
    GET_INVOICE_DATA,
    GET_FILTERED_DATA
};