// create-edit
const GENERATE_NUMBER = 'GENERATE_NUMBER';

// documents
const GET_INVOICES = 'GET_INVOICES';
const GET_DELETED_INVOICES = 'GET_DELETED_INVOICES';
const GET_TOTAL_BY_CURRENCY = 'GET_TOTAL_BY_CURRENCY';
const GET_TOTAL_BY_CURRENCY_STATUS = 'GET_TOTAL_BY_CURRENCY_STATUS';


export default {
    GENERATE_NUMBER,
    GET_INVOICES,
    GET_DELETED_INVOICES,
    GET_TOTAL_BY_CURRENCY,
    GET_TOTAL_BY_CURRENCY_STATUS
};